# Data Exploration

In [1]:
# Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from config import state_abbrev, reverse_state_abbrev, state_codes

import plotly.offline as py
import plotly.graph_objs as go
import plotly.figure_factory as ff
py.init_notebook_mode(connected=True)

In [8]:
# Read in clean datasets
county_aqi_1980_2018 = pd.read_csv('clean_data/county_aqi_1980_2018.csv', index_col=0)
county_cancer_trends = pd.read_csv('clean_data/county_cancer_trends.csv', index_col=0)
state_cancer_1998_2014 = pd.read_csv('clean_data/state_cancer_1998_2014.csv', index_col=0)

In [9]:
county_aqi_1980_2018.head()

,State,County,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,...,State Abbreviation,FIPS,State FIPS Code,County FIPS Code,% Days Good,% Days Moderate,% Days Unhealthy for Sensitive Groups,% Days Unhealthy,% Days Very Unhealthy,% Days Hazardous
0,alabama,autauga,1980,179,122,35,18,4,0,0,...,AL,1001,1,1,68.156425,19.553073,10.055866,2.234637,0.000000,0.0
1,alabama,autauga,1981,357,289,49,15,4,0,0,...,AL,1001,1,1,80.952381,13.725490,4.201681,1.120448,0.000000,0.0
2,alabama,autauga,1982,245,203,36,5,0,1,0,...,AL,1001,1,1,82.857143,14.693878,2.040816,0.000000,0.408163,0.0
3,alabama,autauga,1989,63,54,9,0,0,0,0,...,AL,1001,1,1,85.714286,14.285714,0.000000,0.000000,0.000000,0.0
4,alabama,autauga,1990,266,183,64,18,1,0,0,...,AL,1001,1,1,68.796992,24.060150,6.766917,0.375940,0.000000,0.0

In [10]:
county_cancer_trends.head()

,Geography,FIPS,Met Healthy People Objective of ***?,"Age-Adjusted Incidence Rate(Â†) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend (Â‡) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1,County,State,State Abbreviation
1,"Union County, Florida(6,10)",12125,***,215.1,183.2,251.1,38,stable,-2.5,-24,25,Union County,Florida,FL
2,"Owsley County, Kentucky(7,8)",21189,***,179.7,134.8,236.3,11,rising,4.3,0.9,7.7,Owsley County,Kentucky,KY
3,"McCreary County, Kentucky(7,8)",21147,***,154.1,130.5,180.9,32,stable,-0.7,-3,1.7,McCreary County,Kentucky,KY
4,"North Slope Borough, Alaska(6,10)",2185,***,150.8,97.0,220.1,7,stable,-0.2,-36.8,57.8,North Slope Borough,Alaska,AK
5,"Powell County, Kentucky(7,8)",21197,***,140.9,115.2,171.0,22,stable,0.4,-3.3,4.3,Powell County,Kentucky,KY

In [11]:
state_cancer_1998_2014.head()

,State,State Abbreviation,Year,Year Code,Cancer Sites,Cancer Sites Code,Count
0,Connecticut,CT,1999,1999,All Invasive Cancer Sites Combined,0,18694
1,Connecticut,CT,2000,2000,All Invasive Cancer Sites Combined,0,19200
2,Connecticut,CT,2001,2001,All Invasive Cancer Sites Combined,0,19626
3,Connecticut,CT,2002,2002,All Invasive Cancer Sites Combined,0,19570
4,Connecticut,CT,2003,2003,All Invasive Cancer Sites Combined,0,19516

In [ ]:
values = merged_data['2017 Estimate'].tolist()
fips = merged_data['FIPS'].tolist()

# # colorscale = ["#ff0000","#ff9900","#ffff00","#ccff33","#33cc33", "#bfbfbf"]
# colorscale = ["#bfbfbf","#ff0000","#ff9900","#ffff00","#33cc33", "#bfbfbf"]
colorscale = [
    'rgb(193, 193, 193)',
    'rgb(239,239,239)',
    'rgb(195, 196, 222)',
    'rgb(144,148,194)',
    'rgb(101,104,168)',
    'rgb(65, 53, 132)'
]
# endpts = list(np.mgrid[0:max(values):5j])
binning_endpoints=[14348, 63983, 134827, 426762, 2081313]

fig = ff.create_choropleth(
    fips=fips, values=values, scope=['usa'],
    binning_endpoints = binning_endpoints,colorscale=colorscale,
    show_state_data=False,
    county_outline={'color': 'rgb(0,0,0)', 'width': 0.5},
    show_hover=True, centroid_marker={'opacity': 0},
    asp=2.9, title='USA County Population',
    legend_title='Population'
)
py.iplot(fig, filename='choropleth_full_usa')